name: Telegram POST notifications
on:
  workflow_call:
          
    
jobs:
  send_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare JSON
        run: |
          JSON_PAYLOAD=$(cat <<EOF
          {
            "message": "âŒ GitHub Workflow Notification: Workflow '${{ github.workflow }}' from repository '${{ github.repository }}' failed. View details at: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'"
          }
          EOF
          )
          JSON_PAYLOAD=$(echo $JSON_PAYLOAD | tr -d '\n')
          echo "$JSON_PAYLOAD" > output.json

      - name: Send JSON
        run: |
          curl -X POST ${{ vars.TELEGRAM_REPORTS_PATH }} \
          -H "Content-Type: application/json" \
          --data-binary @output.json